-- V3 feedback table + Row Level Security
-- Public frontend may INSERT only. Anonymous SELECT is intentionally denied.

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  message text not null,
  created_at timestamptz not null default now(),
  constraint feedback_message_length
    check (char_length(btrim(message)) between 1 and 1000)
);

alter table public.feedback enable row level security;

drop policy if exists "anon can insert feedback" on public.feedback;
create policy "anon can insert feedback"
  on public.feedback
  for insert
  to anon
  with check (char_length(btrim(message)) between 1 and 1000);

grant insert on table public.feedback to anon;
grant usage, select on sequence public.feedback_id_seq to anon;
